version: "3.8"

services:
  telegram-bot:
    build: .
    image: midianok/telegram-bot-service:latest
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      INLINE_VOICE_ENABLED: ${INLINE_VOICE_ENABLED}
      REPLY_ENABLED: ${REPLY_ENABLED}
      IMAGE_DISTORTION: ${IMAGE_DISTORTION}
      OWNER_ID: ${OWNER_ID}
    volumes:
      - "./data:/app/data"

volumes:
  data:
    external: true
