version: "3.8"

services:
  telegram-bot:
    build: .
    image: midianok/telegram-bot-service:latest
    environment:
      BOT_TOKEN: ""
      INLINE_VOICE_ENABLED: true
      REPLY_ENABLED: false
      IMAGE_DISTORTION:
      WEBHOOK_URL:
      WEBHOOK_PORT:
    volumes:
      - "./data:/app/data"

volumes:
  data:
    external: true
